export const options = [
	{ value: 'en', label: 'English' },
	{ value: 'fr', label: 'French' },
	{ value: 'de', label: 'German' },
	{ value: 'es', label: 'Spanish' },
	{ value: 'it', label: 'Italian' },
	{ value: 'pt', label: 'Portuguese' },
	{ value: 'zh', label: 'Chinese' },
	{ value: 'ja', label: 'Japanese' },
	{ value: 'ko', label: 'Korean' },
	{ value: 'ru', label: 'Russian' },
	{ value: 'ar', label: 'Arabic' },
	{ value: 'hi', label: 'Hindi' },
	{ value: 'tr', label: 'Turkish' },
	{ value: 'nl', label: 'Dutch' },
	{ value: 'sv', label: 'Swedish' },
	{ value: 'no', label: 'Norwegian' },
	{ value: 'fi', label: 'Finnish' },
	{ value: 'da', label: 'Danish' },
	{ value: 'pl', label: 'Polish' },
]